name: quarks_version_checker
description: Detector automático de nuevas versiones para Flutter Web. By Quarks Studio.
version: 1.1.0
homepage: https://quarks-studio.com
repository: https://github.com/quarks-studio/quarks_version_checker

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  package_info_plus: ^8.0.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0